package com.demo.Models;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="Candidates")
public class Candidates {
	@Id
//the pid values will be autogenerated
@GeneratedValue(strategy=GenerationType.IDENTITY)
@Column(name="cid",length=10)
private int cid;

@Column(name="name",nullable=false,unique=true)

private String cname;
private String cadd;


public Candidates() {
	super();
}
public Candidates(int cid, String cname, String cadd) {
	super();
	this.cid = cid;
	this.cname = cname;
	this.cadd = cadd;
}
public int getCid() {
	return cid;
}
public void setCid(int cid) {
	this.cid = cid;
}
public String getCname() {
	return cname;
}
public void setCname(String cname) {
	this.cname = cname;
}
public String getCadd() {
	return cadd;
}
public void setCadd(String cadd) {
	this.cadd = cadd;
}
@Override
public String toString() {
	return "Candidates [cid=" + cid + ", cname=" + cname + ", cadd=" + cadd + "]";
}
}
